CSL Preferences [WIP]
subhramit/jabref pull request #6
Opened 2024-07-12 22:43 UTC by subhramit

### Mandatory checks

- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [ ] Tests created for changes (if applicable)
- [ ] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [ ] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.

2024-07-12 22:49 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/openoffice/OpenOfficePreferences.java
> +        this.currentStyleType = new SimpleStringProperty(currentStyleType);
Use here the enum directly, e.g. SimpleObjectProperty<StyleType>

2024-07-12 22:50 UTC, Siedlerchr commented on src/main/java/org/jabref/preferences/JabRefPreferences.java
> +                get(OO_BIBLIOGRAPHY_STYLE_TYPE),
For the enum use StyleType.valueOf(get(OO_BIBLIOGRAPHY_STYLE_TYPE))

as a related example for dealing with enums see GroupsPreferences

2024-07-12 22:51 UTC, Siedlerchr commented on src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java
> +        if ("CSL".equals(openOfficePreferences.getCurrentStyleType())) {
If you use the enum value in the preferences you can make this a typesafe check

2024-07-12 22:55 UTC, calixtus commented on src/main/java/org/jabref/gui/openoffice/StyleSelectDialogViewModel.java
> +        if (selectedTab.get().getText().equals("CSL Styles")) {
No magic strings

2024-07-12 22:58 UTC, Siedlerchr requested changes
use enum in prefs

2024-07-12 23:26 UTC, subhramit commented
Applied review changes

2024-07-13 11:31 UTC, Siedlerchr commented on src/main/java/org/jabref/logic/openoffice/style/StyleLoader.java
> +    public class StyleIdentifier {
You now run into the architecture issues I already talked about in the beginning.

Make this an interface.
Let both CSLStyle and OOStyle implement the interface
In the StyleSelectionViewMOdel you then store he concrete style object 
https://docs.oracle.com/en/java/javase/17/language/pattern-matching-instanceof-operator.html 

As an example you can take a look at the PreviewLayout interface and it's subclasses, e.g. CitationStylePreviewLayout   
The latter one also has a path method 


I think this makes it a bit more cleaner and you don't have to do a cast to object

2024-07-21 15:12 UTC, closed without merging